export enum Directions {
    NORTH = 0,
    EAST = 1,
    SOUTH = 2,
    WEST = 3,
};

// Cell types
export enum CellTypes {
    CELL_GRASS    = 0,
    CELL_WATER    = 1,
    CELL_FOREST   = 2,
    CELL_COASTN   = 3,
    CELL_COASTE   = 4,
    CELL_COASTS   = 5,
    CELL_COASTW   = 6,
    CELL_COASTNE  = 7,
    CELL_COASTSE  = 8,
    CELL_COASTSW  = 9,
    CELL_COASTNW  = 10,
    CELL_COASTNE2 = 11,
    CELL_COASTSE2 = 12,
    CELL_COASTSW2 = 13,
    CELL_COASTNW2 = 14,
    CELL_ROCKN    = 15,
    CELL_ROCKE    = 16,
    CELL_ROCKS    = 17,
    CELL_ROCKW    = 18,
    CELL_ROCKNE   = 19,
    CELL_ROCKSE   = 20,
    CELL_ROCKSW   = 21,
    CELL_ROCKNW   = 22,
    CELL_FORESTN   = 23,
    CELL_FORESTE   = 24,
    CELL_FORESTS   = 25,
    CELL_FORESTW   = 26,
    CELL_FORESTNE  = 27,
    CELL_FORESTSE  = 28,
    CELL_FORESTSW  = 29,
    CELL_FORESTNW  = 30,
    CELL_FORESTNE2 = 31,
    CELL_FORESTSE2 = 32,
    CELL_FORESTSW2 = 33,
    CELL_FORESTNW2 = 34,
};

// Cell Edges
export enum CellEdges {
    GRASS    = 0,
    WATER    = 1,
    FOREST   = 2,
    COAST_N  = 3,
    COAST_E  = 4,
    COAST_S  = 5,
    COAST_W  = 6,
    FOREST_N = 7,
    FOREST_E = 8,
    FOREST_S = 9,
    FOREST_W = 10,
    ROCK_N   = 11,
    ROCK_E   = 12,
    ROCK_S   = 13,
    ROCK_W   = 14,
    ROCK     = 15,
}

export const cellRules: Record<CellTypes , Array<CellEdges>> = {
    [CellTypes.CELL_GRASS]   : [CellEdges.GRASS, CellEdges.GRASS, CellEdges.GRASS, CellEdges.GRASS],
    [CellTypes.CELL_WATER]   : [CellEdges.WATER, CellEdges.WATER, CellEdges.WATER, CellEdges.WATER],
    [CellTypes.CELL_FOREST]  : [CellEdges.FOREST, CellEdges.FOREST, CellEdges.FOREST, CellEdges.FOREST],
    [CellTypes.CELL_COASTN]  : [CellEdges.GRASS, CellEdges.COAST_N, CellEdges.WATER, CellEdges.COAST_N],
    [CellTypes.CELL_COASTE]  : [CellEdges.COAST_E, CellEdges.GRASS, CellEdges.COAST_E, CellEdges.WATER],
    [CellTypes.CELL_COASTS]  : [CellEdges.WATER, CellEdges.COAST_S, CellEdges.GRASS, CellEdges.COAST_S],
    [CellTypes.CELL_COASTW]  : [CellEdges.COAST_W, CellEdges.WATER, CellEdges.COAST_W, CellEdges.GRASS],
    [CellTypes.CELL_COASTNE] : [CellEdges.GRASS, CellEdges.GRASS, CellEdges.COAST_E, CellEdges.COAST_N],
    [CellTypes.CELL_COASTSE] : [CellEdges.COAST_E, CellEdges.GRASS, CellEdges.GRASS, CellEdges.COAST_S],
    [CellTypes.CELL_COASTSW] : [CellEdges.COAST_W, CellEdges.COAST_S, CellEdges.GRASS, CellEdges.GRASS],
    [CellTypes.CELL_COASTNW] : [CellEdges.GRASS, CellEdges.COAST_N, CellEdges.COAST_W, CellEdges.GRASS],
    [CellTypes.CELL_COASTNE2]: [CellEdges.COAST_E, CellEdges.COAST_N, CellEdges.WATER, CellEdges.WATER],
    [CellTypes.CELL_COASTSE2]: [CellEdges.WATER, CellEdges.COAST_S, CellEdges.COAST_E, CellEdges.WATER],
    [CellTypes.CELL_COASTSW2]: [CellEdges.WATER, CellEdges.WATER, CellEdges.COAST_W, CellEdges.COAST_S],
    [CellTypes.CELL_COASTNW2]: [CellEdges.COAST_W, CellEdges.WATER, CellEdges.WATER, CellEdges.COAST_N],
    [CellTypes.CELL_ROCKN]   : [CellEdges.ROCK, CellEdges.ROCK_N, CellEdges.GRASS, CellEdges.ROCK_N],
    [CellTypes.CELL_ROCKE]   : [CellEdges.ROCK_E, CellEdges.ROCK, CellEdges.ROCK_E, CellEdges.GRASS],
    [CellTypes.CELL_ROCKS]   : [CellEdges.GRASS, CellEdges.ROCK_S, CellEdges.ROCK, CellEdges.ROCK_S],
    [CellTypes.CELL_ROCKW]   : [CellEdges.ROCK_W, CellEdges.GRASS, CellEdges.ROCK_W, CellEdges.ROCK],
    [CellTypes.CELL_ROCKNE]  : [CellEdges.ROCK_E, CellEdges.ROCK_N, CellEdges.GRASS, CellEdges.GRASS],
    [CellTypes.CELL_ROCKSE]  : [CellEdges.GRASS, CellEdges.ROCK_S, CellEdges.ROCK_E, CellEdges.GRASS],
    [CellTypes.CELL_ROCKSW]  : [CellEdges.GRASS, CellEdges.GRASS, CellEdges.ROCK_W, CellEdges.ROCK_S],
    [CellTypes.CELL_ROCKNW]  : [CellEdges.ROCK_W, CellEdges.GRASS, CellEdges.GRASS, CellEdges.ROCK_N],
    [CellTypes.CELL_FORESTN] : [CellEdges.FOREST, CellEdges.FOREST_N, CellEdges.GRASS, CellEdges.FOREST_N],
    [CellTypes.CELL_FORESTE] : [CellEdges.FOREST_E, CellEdges.FOREST, CellEdges.FOREST_E, CellEdges.GRASS],
    [CellTypes.CELL_FORESTS] : [CellEdges.GRASS, CellEdges.FOREST_S, CellEdges.FOREST, CellEdges.FOREST_S],
    [CellTypes.CELL_FORESTW] : [CellEdges.FOREST_W, CellEdges.GRASS, CellEdges.FOREST_W, CellEdges.FOREST],
    [CellTypes.CELL_FORESTNE]: [CellEdges.FOREST_E, CellEdges.FOREST_N, CellEdges.GRASS, CellEdges.GRASS],
    [CellTypes.CELL_FORESTSE]: [CellEdges.GRASS, CellEdges.FOREST_S, CellEdges.FOREST_E, CellEdges.GRASS],
    [CellTypes.CELL_FORESTSW]: [CellEdges.GRASS, CellEdges.GRASS, CellEdges.FOREST_W, CellEdges.FOREST_S],
    [CellTypes.CELL_FORESTNW]: [CellEdges.FOREST_W, CellEdges.GRASS, CellEdges.GRASS, CellEdges.FOREST_N],
    [CellTypes.CELL_FORESTNE2]: [CellEdges.FOREST, CellEdges.FOREST, CellEdges.FOREST_E, CellEdges.FOREST_N],
    [CellTypes.CELL_FORESTSE2]: [CellEdges.FOREST_E, CellEdges.FOREST, CellEdges.FOREST, CellEdges.FOREST_S],
    [CellTypes.CELL_FORESTSW2]: [CellEdges.FOREST_W, CellEdges.FOREST_S, CellEdges.FOREST, CellEdges.FOREST],
    [CellTypes.CELL_FORESTNW2]: [CellEdges.FOREST, CellEdges.FOREST_N, CellEdges.FOREST_W, CellEdges.FOREST],
};

export const cellWeights = {
    CELL_GRASS    : 16,
    CELL_WATER    : 4,
    CELL_FOREST   : 5,
    CELL_COASTN   : 5,
    CELL_COASTE   : 5,
    CELL_COASTS   : 5,
    CELL_COASTW   : 5,
    CELL_COASTNE  : 5,
    CELL_COASTSE  : 5,
    CELL_COASTSW  : 5,
    CELL_COASTNW  : 5,
    CELL_COASTNE2 : 2,
    CELL_COASTSE2 : 2,
    CELL_COASTSW2 : 2,
    CELL_COASTNW2 : 2,
    CELL_FORESTN  : 4,
    CELL_FORESTE  : 4,
    CELL_FORESTS  : 4,
    CELL_FORESTW  : 4,
    CELL_FORESTNE : 4,
    CELL_FORESTSE : 4,
    CELL_FORESTSW : 4,
    CELL_FORESTNW : 4,
    CELL_FORESTNE2: 2,
    CELL_FORESTSE2: 2,
    CELL_FORESTSW2: 2,
    CELL_FORESTNW2: 2,
    CELL_ROCKN    : 4,
    CELL_ROCKE    : 4,
    CELL_ROCKS    : 4,
    CELL_ROCKW    : 4,
    CELL_ROCKNE   : 4,
    CELL_ROCKSE   : 4,
    CELL_ROCKSW   : 4,
    CELL_ROCKNW   : 4,
};
